cluster_billing_account_name: 'aso'
host_name_from_rig_index: [ 'asolab-ww1.hhmi.org',  'deepmind-ww1.hhmi.org' ]
rig_user_name_from_rig_index: [ 'ASOLAB-WW1+labadmin', 'DEEPMIND-WW1+labadmin' ]
data_folder_path_from_rig_index: [ '/cygdrive/d/Data', '/cygdrive/c/Data' ]
destination_folder: '/groups/aso/asolab/transfero-data'
log_file_name: 'transfero-analysis.log'
user_name_for_configuration_purposes: 'asorobot'
analysis_executable_path: '../aso-deepmind-experiment-analysis-pipeline/aso_deepmind_experiment_analysis_pipeline.py'  
  # this is interpreted relative to folder containing transfero.py
slots_per_analysis_job: 48
maximum_analysis_slot_count: 1920
do_retry_failed_analysis: False
do_transfer_data_from_rigs: True
do_run_analysis: True
launch_hour: 3
launch_minute: 0
