cluster_billing_account_name: 'aso'
host_name_from_rig_index: [ 'asolab-ww1.hhmi.org',  'deepmind-ww1.hhmi.org' ]
rig_user_name_from_rig_index: [ 'ASOLAB-WW1+labadmin', 'DEEPMIND-WW1+labadmin' ]
data_folder_path_from_rig_index: [ '/cygdrive/d/Data', '/cygdrive/c/Data' ]
destination_folder: '/groups/aso/asolab/transfero-data'
does_use_per_user_folders: False 
#analysis_executable_path: '/bin/echo'
analysis_executable_path: '../aso-deepmind-experiment-analysis-pipeline/aso_deepmind_experiment_analysis_pipeline.py'  # this is interpreted realtive to folder containing transfero.py
slots_per_analysis_job: 48
maximum_analysis_slot_count: 480
