cluster_billing_account_name: 'otopalik'
host_name_from_rig_index: [ '10.103.32.21', '10.103.32.26', '10.103.30.36', '10.103.30.38' ]
rig_user_name_from_rig_index: [ 'RUBINLAB-WW11+labadmin', 'RUBINLAB-WW16+labadmin', 'labadmin', 'OTOPALIKLAB-WW6+labadmin' ]
data_folder_path_from_rig_index: [ '/cygdrive/d/Data', '/cygdrive/d/Data', '/cygdrive/d/Data', '/cygdrive/d/Data' ]
destination_folder: '/groups/otopalik/otopaliklab/flydisco_data'
log_file_name: 'flydisco-analysis-log.txt'
user_name_for_configuration_purposes: 'otopalikrobot'
analysis_executable_path: '../FlyDiscoAnalysis/transfero_FlyDiscoPipeline_wrapper_wrapper.py'  
  # this is interpreted relative to folder containing transfero.py
slots_per_analysis_job: 4
maximum_analysis_slot_count: 400
do_retry_failed_analysis: False
do_transfer_data_from_rigs: True
do_run_analysis: True
launch_hour: 22
launch_minute: 0
