cluster_billing_account_name: 'scicompsoft'
host_name_from_rig_index: [ 'taylora-ws1.int.janelia.org' ]
rig_user_name_from_rig_index: [ 'taylora' ]
data_folder_path_from_rig_index: [ '/groups/scicompsoft/home/taylora/yoshi/transfero/test-source-folder' ]
destination_folder: '/groups/scicompsoft/home/taylora/yoshi/transfero/test-destination-folder'
does_use_per_user_folders: False
analysis_executable_path: '/bin/echo'
